export const DATATABLE_CONSTANTS = {
  PRODUCTS: {
    columns: [
      { name: 'ID', prop: 'id' },
      { name: 'Name', prop: 'name' },
      { name: 'Price', prop: 'price' },
      { name: 'Categtory', prop: 'categtory' },
      { name: 'Status', prop: 'status' },
    ],
    data: [
      {
        id: 1,
        name: 'Cricket',
        price: 100,
        categtory: 'Sports',
        status: 'Available',
      },
      {
        id: 2,
        name: 'Football',
        price: 150,
        categtory: 'Sports',
        status: 'Available',
      },
      {
        id: 3,
        name: 'Tennis',
        price: 200,
        categtory: 'Sports',
        status: 'Unavailable',
      },
      {
        id: 4,
        name: 'Basketball',
        price: 250,
        categtory: 'Sports',
        status: 'Available',
      },
      {
        id: 5,
        name: 'Baseball',
        price: 300,
        categtory: 'Sports',
        status: 'Unavailable',
      },
      {
        id: 6,
        name: 'Hockey',
        price: 350,
        categtory: 'Sports',
        status: 'Available',
      },
      {
        id: 7,
        name: 'Golf',
        price: 400,
        categtory: 'Sports',
        status: 'Available',
      },
      {
        id: 8,
        name: 'Rugby',
        price: 450,
        categtory: 'Sports',
        status: 'Unavailable',
      },
      {
        id: 9,
        name: 'Volleyball',
        price: 500,
        categtory: 'Sports',
        status: 'Available',
      },
      {
        id: 10,
        name: 'Badminton',
        price: 550,
        categtory: 'Sports',
        status: 'Available',
      },
      {
        id: 11,
        name: 'Table Tennis',
        price: 600,
        categtory: 'Sports',
        status: 'Unavailable',
      },
      {
        id: 12,
        name: 'Cricket',
        price: 650,
        categtory: 'Sports',
        status: 'Available',
      },
      {
        id: 13,
        name: 'Football',
        price: 700,
        categtory: 'Sports',
        status: 'Available',
      },
      {
        id: 14,
        name: 'Tennis',
        price: 750,
        categtory: 'Sports',
        status: 'Unavailable',
      },
      {
        id: 15,
        name: 'Basketball',
        price: 800,
        categtory: 'Sports',
        status: 'Available',
      },
    ],
  },
  DTOPTIONS: {
    pagingType: 'full_numbers',
    paging: true,
    lengthMenu: [5, 10, 15, 20, 25],
    pageLength: 10,
    ordering: true,
    order: [[0, 'asc']],
    language: {
      search: 'Search',
    },
    responsive: true,
    dom: 'Bfrtip',
    buttons: [
      {
        extend: 'copy',
        className: 'btn btn-primary btn-sm glyphicon glyphicon-duplicate',
      },
      {
        extend: 'csv',
        className: 'btn btn-primary btn-sm glyphicon glyphicon-save-file',
      },
      {
        extend: 'excel',
        className: 'btn btn-primary btn-sm glyphicon glyphicon-list-alt',
      },
      {
        extend: 'pdf',
        className: 'btn btn-primary btn-sm glyphicon glyphicon-file',
      },
      {
        extend: 'print',
        className: 'btn btn-primary btn-sm glyphicon glyphicon-print',
      },
    ],
  },
};
